In [1]:
import numpy as np

In [2]:
a=np.array(range(10))

In [4]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(a)

numpy.ndarray

In [6]:
l1=[5,4,8,10]
b=np.array(l1)
b


array([ 5,  4,  8, 10])

In [7]:
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('int32')

In [10]:
l2=[1,2.0,3,'a']
l2

[1, 2.0, 3, 'a']

In [12]:
np.array(l2) #type을 통일시켜줌!

array(['1', '2.0', '3', 'a'], dtype='<U32')

In [13]:
l3=[1,2,3.0,5.8]
c= np.array(l3)
c

array([1. , 2. , 3. , 5.8])

In [14]:
c.dtype

dtype('float64')

In [15]:
c.shape

(4,)

In [16]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
b

array([ 5,  4,  8, 10])

In [18]:
c

array([1. , 2. , 3. , 5.8])

In [21]:
a.shape #개수가10개다

(10,)

## 차원의 개념

In [35]:
l1=[[1,2],[3,4]]
a=np.array(l1)
a.dtype

dtype('int32')

In [36]:
a.shape

(2, 2)

In [37]:
l2=[[1,2,3],[3,4]] #차원의 개념이 들어가려면 개수가 같아야 한다.
b=np.array(l2)
b


array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [40]:
range(10)

range(0, 10)

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [51]:
np.linspace(10,11,2)

array([10., 11.])

## Shape

In [55]:
a=np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a.shape

(8,)

In [58]:
b=a.reshape(2,4)

In [63]:
b.shape

(2, 4)

### 또 다른 방법

In [65]:
a.shape =(2,4)

In [66]:
a

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [70]:
a.shape=-1 #-1로 하면 다 펼쳐버림

In [71]:
a

array([2, 3, 4, 5, 6, 7, 8, 9])

### astype

In [74]:
a=np.linspace(0,100)

In [75]:
a.dtype

dtype('float64')

In [77]:
b=a.astype(str)
b

array(['0.0', '2.0408163265306123', '4.081632653061225',
       '6.122448979591837', '8.16326530612245', '10.204081632653061',
       '12.244897959183675', '14.285714285714286', '16.3265306122449',
       '18.367346938775512', '20.408163265306122', '22.448979591836736',
       '24.48979591836735', '26.53061224489796', '28.571428571428573',
       '30.612244897959183', '32.6530612244898', '34.69387755102041',
       '36.734693877551024', '38.775510204081634', '40.816326530612244',
       '42.85714285714286', '44.89795918367347', '46.93877551020408',
       '48.9795918367347', '51.02040816326531', '53.06122448979592',
       '55.10204081632653', '57.142857142857146', '59.183673469387756',
       '61.224489795918366', '63.26530612244898', '65.3061224489796',
       '67.34693877551021', '69.38775510204081', '71.42857142857143',
       '73.46938775510205', '75.51020408163265', '77.55102040816327',
       '79.59183673469389', '81.63265306122449', '83.6734693877551',
       '85.71428571428572

In [78]:
c=a.astype(int)
c

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [79]:
np.random.rand(2,3)

array([[0.84246735, 0.3477885 , 0.65568576],
       [0.53226733, 0.1442386 , 0.56497211]])

In [87]:
np.random.randint(1,10,28).reshape(7,4)

array([[3, 4, 7, 9],
       [8, 4, 2, 4],
       [2, 1, 9, 6],
       [9, 2, 6, 1],
       [6, 7, 3, 2],
       [4, 9, 9, 3],
       [6, 6, 3, 5]])

## 인덱스

In [93]:
a= np.linspace(1,20,9)
a

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [94]:
a[8]

20.0

In [96]:
a=a.reshape(3,3)
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [97]:
a[1][2]

12.875

In [98]:
a[1,2]

12.875

In [99]:
a[1:]

array([[ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [100]:
a[:1]

array([[1.   , 3.375, 5.75 ]])

In [101]:
a[:,1:]

array([[ 3.375,  5.75 ],
       [10.5  , 12.875],
       [17.625, 20.   ]])

In [103]:
a[:,:1]

array([[ 1.   ],
       [ 8.125],
       [15.25 ]])

In [106]:
b=a.reshape(-1)
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [107]:
b[1::2]

array([ 3.375,  8.125, 12.875, 17.625])

In [109]:
a[::2,::2]

array([[ 1.  ,  5.75],
       [15.25, 20.  ]])

In [110]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [111]:
a[1,2]

12.875

In [112]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [113]:
b[b>3]

array([ 3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [116]:
arr1=np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr1[(arr1%2)==0]

array([ 2,  4,  6,  8, 10])

In [118]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [119]:
a[1,a[1]>9]

array([10.5  , 12.875])

In [120]:
np.nan

nan

In [121]:
np.inf

inf

## 연산

In [131]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
a+b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [1]:
import numpy as np

In [2]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [3]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [4]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [5]:
print(np.pi)

3.141592653589793


In [6]:
np.zeros(1)

array([0.])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
import random

In [14]:
np.random.rand(2,2)

array([[0.05453187, 0.91464624],
       [0.78040432, 0.81177495]])

In [15]:
np.random.rand(2,3,4)

array([[[0.40744187, 0.4076823 , 0.57370645, 0.90744811],
        [0.57135416, 0.25810211, 0.42553378, 0.24925457],
        [0.624386  , 0.94905536, 0.70500309, 0.0397737 ]],

       [[0.81931757, 0.01513681, 0.32324501, 0.08042965],
        [0.67202617, 0.88719038, 0.03088616, 0.78447229],
        [0.14379349, 0.61484213, 0.15135397, 0.98759781]]])

In [16]:
np.random.rand(2,3,2)

array([[[0.29315024, 0.85980366],
        [0.87242498, 0.59578469],
        [0.30894218, 0.38736597]],

       [[0.79632777, 0.82453941],
        [0.17509123, 0.14525089],
        [0.06137167, 0.30905263]]])

In [17]:
np.random.rand(2,3,1)

array([[[0.71687035],
        [0.5390342 ],
        [0.77269689]],

       [[0.03445015],
        [0.47141457],
        [0.24887107]]])

In [18]:
np.random.rand(4,2,3)

array([[[0.13994793, 0.18233302, 0.58680564],
        [0.44082318, 0.25890868, 0.67385571]],

       [[0.28745742, 0.06604689, 0.78082849],
        [0.94433166, 0.01922953, 0.20402694]],

       [[0.44547463, 0.11838629, 0.46150503],
        [0.64387645, 0.03807887, 0.02557704]],

       [[0.84961946, 0.64077924, 0.26166395],
        [0.49347384, 0.77386855, 0.89402507]]])

In [22]:
l=[1,2,6,8,10]

In [24]:
l1=np.array([1,2,7,123,78,3])

In [25]:
l1>20

array([False, False, False,  True,  True, False])