In [14]:
word_is = ['원숭이', '바나나', '사과', '코끼리']

In [6]:
from collections import defaultdict
import numpy as np

def one_hot_encode(word_is):
    word2idx_dic = defaultdict(lambda:len(word2idx_dic))
    
    for word in word_is:
        word2idx_dic[word]
        print(word2idx_dic)
    
    n_unique_words = len(word2idx_dic)
    one_hot_vectors = np.zeros((len(word_is), n_unique_words))
    
    for i, word in enumerate(word_is):
        index = word2idx_dic[word]
        one_hot_vectors[i, index] += 1
        
    return one_hot_vectors

In [7]:
one_hot_vectors= one_hot_encode(word_is)
one_hot_vectors

defaultdict(<function one_hot_encode.<locals>.<lambda> at 0x0000000005D9C488>, {'원숭이': 0})
defaultdict(<function one_hot_encode.<locals>.<lambda> at 0x0000000005D9C488>, {'원숭이': 0, '바나나': 1})
defaultdict(<function one_hot_encode.<locals>.<lambda> at 0x0000000005D9C488>, {'원숭이': 0, '바나나': 1, '사과': 2})


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# sklearn을 활용한 one-hot encoding

In [16]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

values = array(word_is)
print(values)

label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
print(int_enc)

onehot_enc = OneHotEncoder(sparse = False)
int_enc = int_enc.reshape(len(int_enc), 1)
print(int_enc)
onehot_enc = onehot_enc.fit_transform(int_enc)
print(onehot_enc)

inverted = label_enc.inverse_transform([argmax(onehot_enc[0, :])]) # argmax : 인자 중 가장 큰 값
print(inverted)

['원숭이' '바나나' '사과' '코끼리']
[2 0 1 3]
[[2]
 [0]
 [1]
 [3]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
['원숭이']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [13]:
from collections import defaultdict
import numpy as np


word2idx_dic = defaultdict(lambda:len(word2idx_dic))

for word in word_is:
    word2idx_dic[word]
    print(word2idx_dic)

n_unique_words = len(word2idx_dic)
one_hot_vectors = np.zeros((len(word_is), n_unique_words))

for i, word in enumerate(word_is):
    index = word2idx_dic[word]
    one_hot_vectors[i, index] += 1

one_hot_vectors

defaultdict(<function <lambda> at 0x00000000094E3BF8>, {'원숭이': 0})
defaultdict(<function <lambda> at 0x00000000094E3BF8>, {'원숭이': 0, '바나나': 1})
defaultdict(<function <lambda> at 0x00000000094E3BF8>, {'원숭이': 0, '바나나': 1, '사과': 2})


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])