In [2]:
import torch.cuda # GPU 지원
from torch import Storage # 1차원 배열, single data type 저장소
import torch.nn # NN 모듈s --> Parameter, Container, Layer, Utility
# Hidden layer의 갯수 결정
import torch.nn.functional # NN functions
import torch.nn.init # initialize 
import torch.optim # 최적화 알고리즘
import torch.autograd # Gradient 자동 계산
# grad는 결국 기울기를 나타낸 것

In [3]:
import torch.distributed # 분산처리
import torch.distributions # 분포

import torch.multiprocessing # 멀티프로세싱 모듈 wrapper

In [4]:
import torch.utils 
from torch.utils import bottleneck # Bottleneck 디버깅
from torch.utils import checkpoint 
from torch.utils import cpp_extension # cpp3지원
from torch.utils import data
from torch.utils import dlpack
from torch.utils import model_zoo

In [5]:
import torch.jit # Torch Script

In [6]:
import numpy as np

# 텐서 (Tensor) 기본
- [torch.Tensor](https://pytorch.org/docs/stable/tensors.html)

In [8]:
x = torch.Tensor(2,2) # = torch.FloatTensor
x
# numpy처럼 shape 재구성

tensor([[3.8956e-43, 0.0000e+00],
        [1.4013e-45, 0.0000e+00]])

In [10]:
print('type: ', x.type())
print('size: ', x.size())
# 여기서 size는 shape과 같다
print('개수: ', x.numel())


type:  torch.FloatTensor
size:  torch.Size([2, 2])
개수:  4


In [11]:
# 4차원
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[1.2093e-42],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]],


        [[[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]],

         [[0.0000e+00],
          [0.0000e+00]]]])

In [12]:
print('type: ', x2.type())
print('size: ', x2.size())
print('개수: ', x2.numel())

type:  torch.FloatTensor
size:  torch.Size([4, 3, 2, 1])
개수:  24


# 텐서를 만드는 또 다른 방법

In [13]:
# 영행렬
a = torch.zeros(4, 4)
print('a:', a)

# 일행렬
b = torch.ones(4,4)
print('b:',b)

# 단위 행렬
c = torch.eye(4,4) 
print('c:',c)

# 0과1사이 난수
d = torch.rand(4,4)
print('d:',d)

# 정규분포 추출 N(0,1)
e = torch.randn(4,4)
print('e:',e)


a: tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
b: tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
c: tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
d: tensor([[0.9088, 0.3157, 0.6448, 0.8419],
        [0.6233, 0.0106, 0.8641, 0.4715],
        [0.9561, 0.3243, 0.7532, 0.3250],
        [0.5390, 0.4510, 0.1675, 0.7901]])
e: tensor([[ 0.0888, -0.8374, -0.2358, -0.2908],
        [ 0.8550, -0.5617, -0.2234,  1.3016],
        [-0.2321, -0.3842, -0.1415, -0.1749],
        [-0.7623, -0.3452,  0.0063,  2.4766]])


In [74]:
x3 = torch.arange(0, 3, step=0.3) # np.arange()
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [75]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [76]:
numpy_test = np.array([[5,6],[10,11]])
torch.from_numpy(numpy_test)

tensor([[ 5,  6],
        [10, 11]])

# 인덱싱, 슬라이싱

In [77]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [78]:
x4[0:2,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [79]:
x4[1]

tensor([4., 5., 6.])

In [80]:
x4[0,:]

tensor([1., 2., 3.])

In [82]:
# 값 변경
x4[0:1,:] = torch.Tensor([62,72,80])
x4

tensor([[62., 72., 80.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [91]:
# 값 변경
x4[1] = torch.Tensor([200,78, 89])
x4

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])

In [123]:
# https://pytorch.org/docs/stable/torch.html#torch.split
x5 = torch.split(x4, split_size_or_sections=1,dim=0) # split함.
x5


(tensor([[62., 72., 80.]]),
 tensor([[200.,  78.,  89.]]),
 tensor([[7., 8., 9.]]))

In [124]:
a, b, c = x5

In [125]:
# https://pytorch.org/docs/stable/torch.html#torch.split
x6 = torch.split(x4, split_size_or_sections=1,dim=1) # split함.
x6

(tensor([[ 62.],
         [200.],
         [  7.]]), tensor([[72.],
         [78.],
         [ 8.]]), tensor([[80.],
         [89.],
         [ 9.]]))

In [126]:
y1 = torch.cat((a,b,c), dim=1)
print(y1)
print('size: ', y1.size())

tensor([[ 62.,  72.,  80., 200.,  78.,  89.,   7.,   8.,   9.]])
size:  torch.Size([1, 9])


In [128]:
y2 = torch.cat((a,b,c), dim=0)
print(y2)
print('size: ', y2.size())

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])
size:  torch.Size([3, 3])


In [129]:
# 하나 더 쌓기
y3 = torch.stack(x5, dim=1)
print(y3)
print('size: ', y3.size())

tensor([[[ 62.,  72.,  80.],
         [200.,  78.,  89.],
         [  7.,   8.,   9.]]])
size:  torch.Size([1, 3, 3])


In [134]:
x7 = torch.randn(3,3)
print('x7:',x7)
print()

# mask함수
mask  = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]])
print('mask:', mask)
print()

out = torch.masked_select(x7, mask)
print('masked_select:', out)
print()

x7: tensor([[ 1.0551, -0.6982,  0.3120],
        [-0.4726, -0.1762,  1.1410],
        [-1.8741, -0.6198, -1.0137]])

mask: tensor([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 0]], dtype=torch.uint8)

masked_select: tensor([ 1.0551, -0.4726, -0.1762,  1.1410, -0.6198])



# 차원 변경(Reshape) - View

In [245]:
x8 = torch.zeros(2,2,1)
x8

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [246]:
x8.view(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [247]:
x8.view(-1) # -1 = Automatic

tensor([0., 0., 0., 0.])

In [248]:
x8.view(-1,2)

tensor([[0., 0.],
        [0., 0.]])

In [249]:
x7.view(4)

tensor([0., 0., 0., 0.])

In [250]:
x8 = x7.squeeze() # 1차원 빼기
print('X7:', x7)
print('x7 size:', x7.size())
print()
print('X8:', x8)
print('x8 size:', x8.size())

X7: tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])
x7 size: torch.Size([2, 2, 1])

X8: tensor([[0., 0.],
        [0., 0.]])
x8 size: torch.Size([2, 2])


In [251]:
# unsqueeze(<차원의 index>)
x8.unsqueeze(0)

tensor([[[0., 0.],
         [0., 0.]]])


# 연산

In [252]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
print('x9: ', x9)
print('x10: ', x10)


x9:  tensor([[10., 20., 30.],
        [40., 50., 60.]])
x10:  tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [253]:
print(x9  + x10)
print(x9.add(x10))
print(torch.add(x9, x10))

tensor([[11., 22., 33.],
        [44., 55., 66.]])
tensor([[11., 22., 33.],
        [44., 55., 66.]])
tensor([[11., 22., 33.],
        [44., 55., 66.]])


In [254]:
print(x9 - x10)
print(x9.sub(x10))
print(x10.sub(x9))
print(torch.sub(x10, x9))

tensor([[ 9., 18., 27.],
        [36., 45., 54.]])
tensor([[ 9., 18., 27.],
        [36., 45., 54.]])
tensor([[ -9., -18., -27.],
        [-36., -45., -54.]])
tensor([[ -9., -18., -27.],
        [-36., -45., -54.]])


In [255]:
x10[1] + 12

tensor([16., 17., 18.])

In [256]:

print(x9 * x10)
print(x9.mul(x10))
print(x10.mul(x9))
print(torch.mul(x10, x9))


tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])
tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])
tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])
tensor([[ 10.,  40.,  90.],
        [160., 250., 360.]])


In [257]:
x10 * 10

tensor([[10., 20., 30.],
        [40., 50., 60.]])


# 연산2

In [174]:
# 거듭제곱 - power
x9.pow(2), torch.pow(x9,2), x9 ** 2

(tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]), tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]), tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]))

In [175]:
x9.sqrt()

tensor([[3.1623, 4.4721, 5.4772],
        [6.3246, 7.0711, 7.7460]])

In [183]:
print(x10.log())
print(torch.log(x10))

tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [184]:
print(x9 % 3)
print(x9 / 3)

tensor([[1., 2., 0.],
        [1., 2., 0.]])
tensor([[ 3.3333,  6.6667, 10.0000],
        [13.3333, 16.6667, 20.0000]])


In [192]:
print(x9)
print(x9.sum())
print(x9.sum(0))
print(x9.sum(1))

tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor([50., 70., 90.])
tensor([ 60., 150.])


In [196]:
print(x9)
print(x9.max())
print()
print(x9.max(0))
print()
print(x9.max(1))

tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor(60.)

torch.return_types.max(
values=tensor([40., 50., 60.]),
indices=tensor([1, 1, 1]))

torch.return_types.max(
values=tensor([30., 60.]),
indices=tensor([2, 2]))


In [197]:
print(x9)
print(x9.min())
print()
print(x9.min(0))
print()
print(x9.min(1))

tensor([[10., 20., 30.],
        [40., 50., 60.]])
tensor(10.)

torch.return_types.min(
values=tensor([10., 20., 30.]),
indices=tensor([0, 0, 0]))

torch.return_types.min(
values=tensor([10., 40.]),
indices=tensor([0, 0]))


In [217]:
x10 = torch.tensor([[-1, -2], [3, 4]])
x10

tensor([[-1, -2],
        [ 3,  4]])

In [219]:
x10.abs()

tensor([[1, 2],
        [3, 4]])

In [225]:
x10[1] = torch.Tensor([3, 10])
x10

tensor([[-1, -2],
        [ 3, 10]])

In [227]:
value, index = x10.max(dim = 0)
value, index

(tensor([ 3, 10]), tensor([1, 1]))

In [228]:
value, index = x10.max(dim = 1)
value, index

(tensor([-1, 10]), tensor([0, 1]))

In [229]:
x10.max()

tensor(10)


# 행렬 연산

In [232]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13

(tensor([[ 0.7829, -1.3008,  0.7234, -0.5829, -1.1701],
         [-1.3827,  1.2335, -1.0407,  0.5140,  1.3856],
         [-2.7929, -0.1704, -0.6077, -0.1924,  1.0463]]),
 tensor([[ 0.2712,  1.6258,  0.2338,  1.7179,  0.3410],
         [-1.3887,  1.8452, -0.7450,  0.6177, -0.6398],
         [-0.8481,  1.1615, -0.9776, -0.0290, -0.6173],
         [ 1.7565,  1.3416,  0.0188, -0.6087, -1.6256],
         [ 1.1934,  1.1097, -0.4737,  0.2009, -0.8282]]),
 tensor([[-1.5470, -1.0814, -0.0358],
         [ 1.1073,  1.2456, -1.0482],
         [ 1.5045, -0.4975,  1.9071],
         [-0.4485,  0.3836,  0.3532],
         [-1.2195,  1.7464, -1.3406]]))

In [234]:
# scalar 연산
1.6200 * 1.1375  + 0.3436 * -0.9347 + -0.9112 * 1.3267 + -0.9952 *  -0.0336 + 0.7455 * 1.3210

1.33094226

In [258]:
# 행렬 연산
# matrix-matrix
torch.mm(x11,x12), x11.mm(x12)

(tensor([[-1.0149, -2.3677,  0.9882,  0.6402,  2.5692],
         [ 1.3512,  1.0466, -0.8714, -1.6177, -2.6014],
         [ 0.9053, -4.6581, -0.4311, -4.5583, -1.0219]]),
 tensor([[-1.0149, -2.3677,  0.9882,  0.6402,  2.5692],
         [ 1.3512,  1.0466, -0.8714, -1.6177, -2.6014],
         [ 0.9053, -4.6581, -0.4311, -4.5583, -1.0219]]))

In [259]:
# matrix-matrix
x11.mm(x12).mm(x13)

tensor([[ -2.9852,   2.3894,   1.1845],
        [  1.6556,  -4.8878,   0.1087],
        [ -3.9160, -10.1000,   3.7881]])

In [260]:
x11.mm(x12).mm(x13).mm(x11)

tensor([[-8.9491,  6.6286, -5.3658,  2.7403,  8.0432],
        [ 7.7507, -8.2011,  6.2180, -3.4984, -8.5962],
        [ 0.3193, -8.0097,  5.3758, -3.6383, -5.4492]])

In [264]:
x14 = torch.randn(3, 4)
v = torch.randn(4)

x14, v

(tensor([[-2.7006e-01, -6.0845e-01, -1.8835e+00, -1.3482e+00],
         [-1.2030e-03,  8.3180e-01,  1.6448e+00,  8.2850e-01],
         [ 1.0982e+00, -1.0535e+00,  4.4572e-01, -2.3781e-01]]),
 tensor([-2.1022,  0.9369,  0.0276, -0.5177]))

In [265]:
-0.4594 * 0.6623 + -1.1798 * 0.2916 +0.3812 * 0.0409+ -0.0064 *  -1.1908

-0.6250781

In [269]:
# # matrix-vector = mv
torch.mv(x14,v), x14.mv(v)

(tensor([ 0.6436,  0.3983, -3.1603]), tensor([ 0.6436,  0.3983, -3.1603]))

In [274]:
x15 = torch.randn(10,3,4)
x16 = torch.randn(10,4,5)

# batch matrix-matrix product
# (10,3,4).(10,4,5) => (10,3,5)
torch.bmm(x15, x16).size()

torch.Size([10, 3, 5])

In [276]:
torch.bmm(x15, x16)

tensor([[[-1.0368e+00, -1.3805e+00,  1.4497e+00, -6.5166e-01,  1.5449e+00],
         [ 5.3111e-01, -1.0754e+00, -2.3721e+00,  1.0660e+00, -1.9660e+00],
         [-1.8556e+00, -3.8023e+00,  2.3765e+00, -2.5852e+00,  1.0282e+00]],

        [[-1.9161e+00,  1.6962e+00, -7.1003e-01,  9.1192e-01, -1.5393e-02],
         [ 1.7731e+00,  2.8775e-01,  1.1370e+00,  3.5155e-01, -1.1751e-01],
         [-1.1457e+00,  3.3178e+00,  8.9007e-01,  5.5415e-01, -1.5015e+00]],

        [[-7.1784e-01, -2.5677e+00, -1.2720e+00,  1.1556e+00,  1.3869e+00],
         [ 1.2873e-01, -6.9090e-01, -6.5750e-01, -2.2922e-01, -4.6528e-01],
         [ 8.9016e-01, -1.1172e+00,  1.3369e+00,  7.5720e-01, -1.3090e-01]],

        [[ 6.1198e-01, -1.0780e-01,  2.1395e-02, -1.2018e+00, -2.1265e+00],
         [-9.7739e-03, -3.2453e-01,  3.3705e-01, -4.3391e-01,  2.3086e+00],
         [-4.0439e-01,  5.4500e-01,  5.2649e-01, -1.5866e-01, -1.5107e+00]],

        [[-1.5700e+00,  5.7975e-01,  1.7306e-01,  4.4301e+00,  1.3354e+00],
    

In [280]:
x17 = torch.randn(2,2)
x18 = torch.randn(2,2)

print(x17)
print(x18)


tensor([[1.7869, 0.6811],
        [1.0960, 0.1544]])
tensor([[ 3.2566, -0.2137],
        [ 0.3911, -1.7526]])


In [285]:
print(x17.view(-1))
print(x18.view(-1))

tensor([1.7869, 0.6811, 1.0960, 0.1544])
tensor([ 3.2566, -0.2137,  0.3911, -1.7526])


In [288]:
# Computes the dot product (inner product) of two tensors.
# 내적
torch.dot(x17.view(-1), x18.view(-1))

tensor(5.8318)

In [293]:
x19  = torch.rand(3,4)

print(x19)
print(x19.size())
print()
print(x19.t())
print(x19.t().size())

tensor([[0.3753, 0.1222, 0.7155, 0.0280],
        [0.8607, 0.6384, 0.2437, 0.2611],
        [0.9290, 0.5042, 0.7229, 0.3840]])
torch.Size([3, 4])

tensor([[0.3753, 0.8607, 0.9290],
        [0.1222, 0.6384, 0.5042],
        [0.7155, 0.2437, 0.7229],
        [0.0280, 0.2611, 0.3840]])
torch.Size([4, 3])


In [326]:
# distane (norm)
x1 = torch.tensor([1., 1.])
x2 = torch.tensor([5, 5.])

torch.dist(x1, x2, 2)
torch.dist(x1, x2, 2)**2

tensor(32.0000)

## Tensor Data Type

In [330]:
x20 = torch.rand(2,2)
x20

tensor([[0.2013, 0.3162],
        [0.6908, 0.9424]])

In [331]:
x20  = torch.LongTensor([1,1])
x20

tensor([1, 1])

In [332]:
x20.float()

tensor([1., 1.])

In [333]:
x20.double()

tensor([1., 1.], dtype=torch.float64)

In [334]:
x20.byte()

tensor([1, 1], dtype=torch.uint8)

In [336]:
x20

tensor([1, 1])

In [341]:
# GPU -> CPU
x20 = x20.cpu()
x20

tensor([1, 1])

In [343]:
# to numpy
x20.numpy()

array([1, 1])

In [344]:
torch.from_numpy(np.random.rand(3,2))

tensor([[0.5944, 0.7538],
        [0.5806, 0.2959],
        [0.1462, 0.1123]], dtype=torch.float64)