## 학습데이터 준비하기 - p.61

In [60]:
import torch
# from torch.autograd import Variable # Deprecated -> Torch에 지원
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset # DataLoader, TensorDataset : 합쳐주는 애

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split

import pandas as pd

In [61]:
wine = load_wine()
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [62]:
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df.head(3)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0

In [63]:
df.shape

(178, 13)

In [64]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [72]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [73]:
wine_data = wine.data[:130]
wine_data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.179e+01, 2.130e+00, 2.780e+00, ..., 9.700e-01, 2.440e+00,
        4.660e+02],
       [1.237e+01, 1.630e+00, 2.300e+00, ..., 8.900e-01, 2.780e+00,
        3.420e+02],
       [1.204e+01, 4.300e+00, 2.380e+00, ..., 7.900e-01, 2.570e+00,
        5.800e+02]])

In [74]:
wine_target = wine.target[:130]
wine_target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [68]:
train_X, test_X, train_y, test_y = train_test_split(wine_data, wine_target, test_size=.2)

In [69]:
print(train_X.shape)
print(test_X.shape)

(104, 13)
(26, 13)


## 텐서 생성 - P.64

In [70]:
# This is the Code
# tensor from numpy
train_X = torch.from_numpy(train_X).float() # double(float64)->float(float32)
train_y = torch.from_numpy(train_y) # long -> long (int64)

In [71]:
test_X = torch.from_numpy(test_X).float()
test_y = torch.from_numpy(test_y)

In [56]:
print(train_X.size()) # ->104행 13열 (2차원배열)
print(train_y.size()) # ->104행 1열  (1차원배열)

torch.Size([104, 13])
torch.Size([16])


In [38]:
# This is the Code
train = TensorDataset(train_X, train_y) # like Dataframe

In [39]:
train

In [40]:
train.tensors

(tensor([[1.4380e+01, 3.5900e+00, 2.2800e+00,  ..., 1.0400e+00, 3.4400e+00,
          1.0650e+03],
         [1.2370e+01, 1.2100e+00, 2.5600e+00,  ..., 1.1900e+00, 2.3000e+00,
          6.7800e+02],
         [1.1960e+01, 1.0900e+00, 2.3000e+00,  ..., 9.9000e-01, 3.1300e+00,
          8.8600e+02],
         ...,
         [1.1760e+01, 2.6800e+00, 2.9200e+00,  ..., 1.2300e+00, 2.5000e+00,
          6.0700e+02],
         [1.1790e+01, 2.1300e+00, 2.7800e+00,  ..., 9.7000e-01, 2.4400e+00,
          4.6600e+02],
         [1.2290e+01, 2.8300e+00, 2.2200e+00,  ..., 1.1500e+00, 3.3000e+00,
          2.9000e+02]]),
 tensor([0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1,
         1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
         1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
         0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
         0, 0, 1, 0, 1, 1, 1, 1], dtype=torch.int32))

In [41]:
print("train_X", train.tensors[0].size())
print("train_y", train.tensors[1].size())

train_X torch.Size([104, 13])
train_y torch.Size([104])


In [42]:
# This is the Code
train_loader = DataLoader(train, batch_size=16, shuffle=True) 
train_loader

## 신경망 구성 - P.67

In [43]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(13, 96) # 입력층 - 중간층
        self.fc2 = nn.Linear(96, 2)  # 중간층 - 출력층
        
    def forward(self, x):
        # forward propagation - FP
        x = F.relu(self.fc1(x)) # 중간층 - Activate Function 
        x = self.fc2(x)
        # Classification Problem
        return F.log_softmax(x, dim=1) # 출력층 - Activate Function 
        # return F.log_softmax(x, dim=None)

In [44]:
model = Net()

## 모형 학습 - P.69

In [48]:
# Cross Entropy Loss(Cost) Function = logistic의 cost 구하는 함수
criterion = nn.CrossEntropyLoss()
# metric = nn.CrossEntropyLoss()

In [49]:
# Stochastic Gradient Decent
optimizer = optim.SGD(model.parameters(), lr=0.01) # learning late

In [53]:
for i in model.parameters():
    print(i)

Parameter containing:
tensor([[-0.0005, -0.0358, -0.2372,  ...,  0.0861, -0.2126, -0.0163],
        [-0.1543, -0.0233, -0.1496,  ..., -0.2156,  0.2172, -0.1091],
        [-0.1967, -0.1795, -0.1148,  ..., -0.2408, -0.0911, -0.0739],
        ...,
        [-0.2286, -0.1407, -0.2073,  ...,  0.2197,  0.1582,  0.2082],
        [ 0.2765,  0.0928, -0.0935,  ..., -0.0879, -0.0221, -0.1903],
        [ 0.1410, -0.0950, -0.2453,  ...,  0.2268, -0.1439, -0.1540]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0025,  0.0130, -0.0310,  0.1632,  0.1999, -0.2651, -0.0774,  0.1937,
         0.2662, -0.2576, -0.0532,  0.2737, -0.2024,  0.0280,  0.2685,  0.1305,
        -0.2086,  0.1279,  0.0675,  0.1036,  0.0998,  0.2087, -0.2631, -0.1048,
        -0.2646,  0.1333, -0.0492,  0.1275,  0.0961, -0.1090, -0.1009,  0.1998,
        -0.2648, -0.1251, -0.2275, -0.2103,  0.1245,  0.1596, -0.1747, -0.1230,
         0.0876,  0.1886, -0.2362,  0.0611, -0.2675, -0.0242,  0.2235, -0.2233,
         0.0174

In [47]:
# epoch은 얼만큼 반복시키느냐!!
for epoch in range(300):
    total_loss = 0
    
    for train_x, train_y in train_loader:
        # train_x, train_y = Variable(train_x), Variable(train_y) # Deprecated
        
        optimizer.zero_grad() # reset gradient
        
        output = model(train_x)
        
        loss = criterion(output, train_y)
        
        loss.backward()
        
        optimizer.step()
        
        # total_loss += loss.data[0]
        total_loss += loss.item()
    if (epoch+1) % 50 == 0:
        print(epoch+1, total_loss)
        print("="*40)

RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target'

In [292]:
type(test_X)

torch.Tensor

In [294]:
# 출력이 0 혹은 1이 되게 함
# result = torch.max(model(test_X), 1)[1]
result = torch.max(model(test_X), 1).indices

#정확도 측정
accuracy = sum(test_y.data.numpy() == result.numpy()) / len(test_y.data.numpy())
accuracy

0.6153846153846154