# 1. Tensor

In [1]:
import torch

In [2]:
print(torch.__version__)

1.0.1


## 1.1 Tensor Basic

In [18]:
#Tensor의 기초적 선언
#torch.FloatTensor와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)

tensor([[1.0650e-42, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [19]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size()) # = x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [21]:
y = torch.IntTensor(2, 4)
# IntTensor는 적용 모델에 적용 시킬 때 안 들어가는 경우가 많다.
print(y)

tensor([[ 43845017,         0, 123573912,         0],
        [123573912,         0,         0,         1]], dtype=torch.int32)


In [22]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(y))
print("Tensor Type : ", y.type())
print("Tensor Size : ", y.size()) # = x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 4])


## 1.2 특별한 Tensor

In [23]:
#0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [24]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [25]:
#1로 채워진 Tensor 선언
x = torch.ones(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [27]:
#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0.4758, 0.8151, 0.1965],
        [0.4104, 0.6944, 0.0272]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [28]:
#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[ 0.9075, -0.7475, -1.2598],
        [-1.1375,  0.8743,  1.4650]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [29]:
#단위행렬과 같은 Tensor 선언
x = torch.eye(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [30]:
#0부터 2까지 0.5씩 증가하는 Tensor 선언

x = torch.arange(0, 2, 0.5)
# x = torch.arange(0, 2, step=0.5)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([4])


In [31]:
#직접 값을 입력하여 선언
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [32]:
#32-bit floating point
x = torch.FloatTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1.0846e-42, 0.0000e+00, 4.3962e-37],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [33]:
#32-bit integer (signed)
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[     776,        0, 51746784],
        [       0,        0,        0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


## 1.3 브릿지 Tensor & Numpy

In [34]:
import numpy as np

In [35]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [36]:
#numpy를 tensor로 변환
y = torch.from_numpy(x) # x = torch.Tensor(x)
print(y)
print("Tensor Type : ", y.type())
print("Tensor Size : ", y.size())

tensor([[1, 2, 3],
        [1, 2, 3]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [37]:
#tensor를 numpy로 변환
z = y.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## 1.4 Tensor Slicing

In [38]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [39]:
#모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [40]:
#2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [41]:
#2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [42]:
#2행, 2열부터 3열까지 출력
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [43]:
#1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [44]:
#x를 1행씩 잘라서 배열의 Tuple로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [45]:
#x를 2열씩 잘라서 배열의 Tuple로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [46]:
#위와 같은 결과
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]), tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [47]:
a=torch.ByteTensor([[0,1],[1,0],[0,1]])
a

tensor([[0, 1],
        [1, 0],
        [0, 1]], dtype=torch.uint8)

In [49]:
x_cols[0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [71]:
#x_cols의 첫번째 배열 중 특정 부분만 추출하기
torch.masked_select(x_cols[0], torch.ByteTensor([[0,1],[1,0],[0,1]]))
# ByteTensor는 byte형의 tensor이다. 0과 1의 값만 가질 수 있다.

tensor([ 2.,  5., 10.])

## 1.5 Tensor 합치기

#### cat: 차원 유지

In [50]:
x_rows

(tensor([[1., 2., 3., 4.]]),
 tensor([[5., 6., 7., 8.]]),
 tensor([[ 9., 10., 11., 12.]]))

In [51]:
#x_rows를 행으로 이어 붙이기
torch.cat(x_rows, dim=0) # dim: axis와 같음 

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [52]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1) # dim: axis와 같음 

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [54]:
x_cols

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]), tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [55]:
x_col1, x_col2 = x_cols

In [56]:
print(x_col1, x_col2, sep='\n')

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])


#### Stack: 차원 확대

In [58]:
#x_cols를 쌓아올리기
x_new = torch.stack([x_col1, x_col2], dim=0) # dim: axis와 같음 
print(x_new)
print(x_new.size())

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])
torch.Size([2, 3, 2])


In [59]:
#x_cols를 쌓아올리기
x_new = torch.stack([x_col1, x_col2], dim=1) # dim: axis와 같음 
print(x_new)
print(x_new.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])
torch.Size([3, 2, 2])


## 1.6 Tensor Reshaping

In [60]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [62]:
#4행 3열로 바꾸기 # reshpae과 같음
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [63]:
#2열로 바꾸기
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [64]:
y = x.view(2, 1, -1)
print(y)
print("Size:", y.size())

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])
Size: torch.Size([2, 1, 6])


In [65]:
#차원이 1인 값을 축소
y = x.view(2, 1, -1).squeeze()
print(y)
print("Size:", y.size())

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])
Size: torch.Size([2, 6])


In [66]:
#dim=1 자리에 차원을 추가
y = x.view(2, 1, -1).squeeze().unsqueeze(dim=1)
print(y)
print("Size:", y.size())

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])
Size: torch.Size([2, 1, 6])


In [162]:
#dim=2 자리에 차원을 추가 (차원)
y = x.view(2, 1, -1).squeeze().unsqueeze(dim=2)
print(y)
print("Size:", y.size())

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.]],

        [[ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]])
Size: torch.Size([2, 6, 1])


## 1.7 GPU를 위한 Tensor - Cuda
#### CUDA(Computed Unified Device Architecture)
#### NVIDIA만 가능

In [67]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [68]:
# cuda 확인
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 0
현재 Cuda 사용 가능 여부 : False


AssertionError: Torch not compiled with CUDA enabled

In [69]:
# cuda 세팅
torch.cuda.set_device(0)

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

In [70]:
#cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

AssertionError: Torch not compiled with CUDA enabled

In [71]:
#cpu를 gpu로 전환 2
device = torch.device("cuda")
gpu_x = x.to(device)
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

AssertionError: Torch not compiled with CUDA enabled

In [72]:
#gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

NameError: name 'gpu_x' is not defined

In [73]:
#gpu를 cpu로 전환 2
device = torch.device("cpu")
x = gpu_x.to(device)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

NameError: name 'gpu_x' is not defined

In [74]:
# gpu tensor와 cpu tensor의 연산
gpu_x + x

NameError: name 'gpu_x' is not defined

## 1.8 Tensor 연산

In [75]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [76]:
# x와 y의 합
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [77]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [78]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [79]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [80]:
#x의 원소에 log를 씌움
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [81]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [82]:
#x의 원소에 나머지(mod) 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [83]:
#x에 절댓값
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 1.9 Tensor 타입변환(Casting)

In [84]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [85]:
x.type(torch.DoubleTensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [86]:
x.double()

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [87]:
x.type(torch.IntTensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [88]:
x.int()

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 1.10 Tensor 통계연산(Statistic)

In [89]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [90]:
print("x의 합 :", x.sum())
print("x의 최대값 :", x.max())
print("x의 최소값 :", x.min())
print("x의 분산 :", x.var())

x의 합 : tensor(3.)
x의 최대값 : tensor(6.)
x의 최소값 : tensor(-5.)
x의 분산 : tensor(17.9000)


In [91]:
# Scalar Tensor
# scalar는 차원이 없음
x.sum().size() 

torch.Size([])

In [92]:
# item의 활용
print("x의 합 :", x.sum().item())
print("x의 최대값 :", x.max().item())
print("x의 최소값 :", x.min().item())
print("x의 분산 :", x.var().item())

x의 합 : 3.0
x의 최대값 : 6.0
x의 최소값 : -5.0
x의 분산 : 17.899999618530273


In [93]:
#행을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value

tensor([4., 2., 6.])

In [94]:
#열을 기준으로 행의 최댓값을 출력
x.max(dim=1)

(tensor([2., 6.]), tensor([1, 2]))

In [95]:
#열을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 1.11 Tensor function (*_like )
#### 모양이 같음

In [96]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [97]:
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [98]:
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [99]:
y = torch.rand_like(x)
print(y)

tensor([[9.7800e-02, 4.3069e-01, 3.8181e-01],
        [4.4617e-01, 2.1851e-04, 2.4764e-01]])


## 1.12 Tensor 행렬연산 

In [100]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print("x :", x)
print("y :", y)

x : tensor([[1., 1.],
        [2., 2.]])
y : tensor([[1., 2.],
        [3., 4.]])


In [101]:
#x와 y의 행렬곱 - multiply matrix
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [102]:
#x와 z의 행렬벡터곱 - Multiply Vector
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

In [103]:
z

tensor([1., 2.])

In [104]:
#z와 z의 내적
torch.dot(z, z)

tensor(5.)

In [105]:
#x의 전치(transpose)
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [106]:
# y의 역행렬(inverse)
y.inverse()

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])